from wireless.envs.time_freq_resource_allocation_v88 import TimeFreqResourceAllocationV87
from wireless.envs.noma_ul_time_freq_resource_allocation_v0 import NomaULTimeFreqResourceAllocationV0
from wireless.envs.umts_olpc import UlOpenLoopPowerControl
